name: Deploy Yaari Frontend to S3

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # react app 'apps/web' folder me hai
    defaults:
      run:
        working-directory: ./apps/web

    steps:
      # Updated to v4 (Modern GitHub Standard)
      - name: Checkout Code
        uses: actions/checkout@v4

      # Updated to v4 and synced with local Node version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      # Updated to v4 (Handles the latest AWS SDKs without deprecation warnings)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
